main:
  - name: Home
    url: /
    weight: 1
    params:
      icon: home

  - name: Sobre
    pageRef: /page/about
    weight: 2
    params:
      icon: user

  - name: Artigos
    url: /archives
    weight: 3
    params:
      icon: archives

  - name: Busca
    url: /search
    weight: 4
    params:
      icon: search

social:
  - identifier: github
    name: GitHub
    url: "https://github.com/ocoelhogabriel"
    weight: 1
    params:
      icon: brand-github

  - identifier: linkedin
    name: LinkedIn
    url: "https://linkedin.com/in/ocoelhogabriel"
    weight: 2
    params:
      icon: brand-linkedin
